# H2 ?????? ??
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test\
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

  # SQL ?? ??
  jpa:
    show-sql: false

    # ??? ?? ??
    hibernate:
      ddl-auto: update

    # SQL ?? ??
    properties:
      hibernate:
        format_sql: true
