# H2 ?????? ??
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  # SQL ?? ??
  jpa:
    show-sql: true

    # ??? ?? ??
    hibernate:
      ddl-auto: update

    # SQL ?? ??
    properties:
      hibernate:
        format_sql: true
