name: Spring Gradle CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code #코드 오류 검토
        uses: actions/checkout@v2

      - name: Set up JDK 11 #JAVA 설정
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Gradle packages # GRADLE 패키징
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Gradle Build without Tests #빌드 테스트
        run: |
          cd Gserver
          chmod +x ./gradlew
          ./gradlew build -x test

      # CD (NCP)
      - name: Deploy to NCP
        env:
          PRIVATE_KEY: ${{ secrets.NCP_SERVER_KEY }}
          HOST: 101.101.161.237 #NCP접속 IP
          USER: root #NCP접속 유저
          GIT_DIR: /root/Gserver
          GRADLE_DIR: /root/Gserver/Gserver
          JAR_DIR: build/libs/Gserver-0.0.1-SNAPSHOT.jar
        run: |## 현재 개인키 인증 오류때문에 비밀번호방식으로 진행 (추후 보안때문에 변경요망) (sshpass)
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          sudo apt-get install sshpass
          sshpass -p 'yechan1460' ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST -p 2222 "\ 
            cd $GIT_DIR && git pull; \
            cd $GRADLE_DIR && ./gradlew build -x test  \
            pkill -f java && nohup java -jar $JAR_DIR & \
          "
          rm -f private_key.pem
