name: Spring Gradle CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Gradle Build without Tests
        run: |
          cd Gserver
          chmod +x ./gradlew
          ./gradlew build

      # 추가된 배포 스텝 (NCP 인스턴스 예시)
      - name: Deploy to NCP
        env:
          PRIVATE_KEY: ${{ secrets.NCP_SERVER_KEY }}
          HOST: 101.101.161.237 #NCP접속 IP
          USER: root #NCP접속 유저
          GIT_DIR: /root/Gserver
          GRADLE_DIR: /root/Gserver/Gserver
          JAR_DIR: build/libs/Gserver-0.0.1-SNAPSHOT.jar
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem $USER@$HOST -p 2222 "\
            cd $GIT_DIR && git pull; \
            cd $GRADLE_DIR && pkill -f java; \
            nohup java -jar $JAR_DIR & \
          "
          rm -f private_key.pem
